<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?

<center>
<h1>Site em Desenvolvimento</h1>
<p>
    Obrigado por visitar o site da Vegan Alimentos.<br>
    Em breve nosso ecommerce estará disponível para todos clientes de maneira prática, rápida e segura.<br>
    Enquanto isso, nos siga nas redes socias ou entre em contato:<br><br>
    <a href="https://fb.com/veganindbr" style="text-decoration: none">
         <img alt="Qries" src="https://cdn4.iconfinder.com/data/icons/social-media-2070/140/_facebook-128.png" width="60" height="50">
    </a>&#160;&#160;&#160;&#160;
    <a href="https://instagr.am/veganindbr" style="text-decoration: none">
         <img alt="Qries" src="https://cdn4.iconfinder.com/data/icons/social-media-2070/140/_instagram-256.png" width="60" height="50">
    </a>&#160;&#160;&#160;&#160;
    <a href="https://twitter.com/veganindbr" style="text-decoration: none">
         <img alt="Qries" src="https://cdn4.iconfinder.com/data/icons/social-media-2070/140/_twitter-256.png" width="60" height="50">
    </a><br><br>
    <a href="mailto:contato@vegan.ind.br" style="text-decoration: none">
         <img alt="Qries" src="https://cdn4.iconfinder.com/data/icons/social-media-2070/140/_unread_email-128.png" width="20" height="20"> contato@vegan.ind.br
    </a><br><br>
    <a href="whatsapp://send?abid=+5561996220406" style="text-decoration: none">
         <img alt="Qries" src="https://cdn4.iconfinder.com/data/icons/social-media-2070/140/_whatsapp-256.png" width="20" height="20"> (061) 3060-0990
    </a>
</p>
