<div class="block-group box-section">
	<div class="us-tes">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('us_block')->toHtml();?>
				</div>
				<div class="col-md-6 col-sm-6 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Testimonial\Block\Testimonial')->setTemplate('testimonial.phtml')->toHtml();?> 
				</div>
			</div>
		</div>
	</div>
	<div class="best_block">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-sm-12 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('best_static')->toHtml();?>
				</div>
				<div class="col-md-4 col-sm-12 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Bestsellerproduct\Block\Bestsellerproduct')->setTemplate('bestsellerproduct.phtml')->toHtml();?> 
				</div>
			</div>
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_block')->toHtml();?>			
		</div>
	</div>
	<div class="blog-slider">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('sidebar/slider.phtml')->toHtml();?> 
	</div>
	<div class="brand-slider">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Brandslider\Block\Brandslider')->setTemplate('brandslider.phtml')->toHtml();?> 
	</div>
</div>